export const UPDATE_POST_MODAL_POST = 'POST_MODAL_POST/UPDATE_POST_MODAL_POST';
export const SHOW_POST_MODAL_POST_LOADING = 'POST_MODAL_POST/SHOW_POST_MODAL_POST_LOADING';
export const HIDE_POST_MODAL_POST_LOADING = 'POST_MODAL_POST/HIDE_POST_MODAL_POST_LOADING';
export const HIDE_POST_MODAL_POST_ERROR = 'POST_MODAL_POST/HIDE_POST_MODAL_POST_ERROR';
export const SHOW_POST_MODAL_POST_ERROR = 'POST_MODAL_POST/SHOW_POST_MODAL_POST_ERROR';
