export const UPDATE_AUTHORIZED_USER_ID = 'LOGIN/UPDATE_AUTHORIZED_USER_ID';
export const UPDATE_AUTHORIZED_USER_DATA = 'LOGIN/UPDATE_AUTHORIZED_USER_DATA';
export const SHOW_AUTHORIZATION_LOADING = 'LOGIN/SHOW_AUTHORIZATION_LOADING';
export const HIDE_AUTHORIZATION_LOADING = 'LOGIN/HIDE_AUTHORIZATION_LOADING';
export const LOAD_AUTHORIZATION_ERROR = 'LOGIN/LOAD_AUTHORIZATION_ERROR';
export const UPDATE_AUTHORIZATION_INPUT_VALUE = 'LOGIN/UPDATE_AUTHORIZATION_INPUT_VALUE';
export const RESET_AUTHORIZED_USER = 'LOGIN/RESET_AUTHORIZED_USER';
export const RESET_AUTHORIZATION_ERROR = 'LOGIN/RESET_AUTHORIZATION_ERROR';
