export const UPDATE_POSTS_LIST = 'POSTS_LIST/UPDATE_POSTS_LIST';
export const SHOW_POSTS_LIST_LOADING = 'POSTS_LIST/SHOW_POSTS_LIST_LOADING';
export const HIDE_POSTS_LIST_LOADING = 'POSTS_LIST/HIDE_POSTS_LIST_LOADING';
export const LOAD_POSTS_LIST_ERROR = 'POSTS_LIST/LOAD_POSTS_LIST_ERROR';
export const UPDATE_POSTS_LIST_PAGE = 'POSTS_LIST/UPDATE_POSTS_LIST_PAGE';
