export const LOAD_USER_INFO = 'USER_INFO/LOAD_USER_INFO';
export const SHOW_USER_INFO_LOADING = 'USER_INFO/SHOW_USER_INFO_LOADING';
export const HIDE_USER_INFO_LOADING = 'USER_INFO/HIDE_USER_INFO_LOADING';
export const SHOW_USER_INFO_ERROR = 'USER_INFO/SHOW_USER_INFO_ERROR';
export const HIDE_USER_INFO_ERROR = 'USER_INFO/HIDE_USER_INFO_ERROR';
