export const OPEN_POST_MODAL = 'POST_MODAL/OPEN_POST_MODAL';
export const CLOSE_POST_MODAL = 'POST_MODAL/CLOSE_POST_MODAL';
export const SET_POST_MODAL_CURRENT_ID = 'POST_MODAL/SET_POST_MODAL_CURRENT_ID';
