export const LOAD_USER_CARD = 'USER_CARD/LOAD_USER_CARD';
export const LOAD_USER_CARD_ERROR = 'USER_CARD/LOAD_USER_CARD_ERROR';
export const SHOW_USER_CARD_LOADING = 'USER_CARD/SHOW_USER_CARD_LOADING';
export const HIDE_USER_CARD_LOADING = 'USER_CARD/HIDE_USER_CARD_LOADING';
