export const UPDATE_USER_POSTS = 'USER_POSTS/UPDATE_USER_POSTS';
export const SHOW_USER_POSTS_LOADING = 'USER_POSTS/SHOW_USER_POSTS_LOADING';
export const HIDE_USER_POSTS_LOADING = 'USER_POSTS/HIDE_USER_POSTS_LOADING';
export const UPDATE_USER_POSTS_PAGE = 'USER_POSTS/UPDATE_USER_POSTS_PAGE';
export const SHOW_USER_POSTS_ERROR = 'USER_POSTS/SHOW_USER_POSTS_ERROR';
export const HIDE_USER_POSTS_ERROR = 'USER_POSTS/HIDE_USER_POSTS_ERROR';
