export const UPDATE_CURRENT_PAGE = "APP/UPDATE_CURRENT_PAGE";
export const UPDATE_PER_PAGE_LIMIT = "APP/UPDATE_PER_PAGE_LIMIT";
export const UPDATE_IS_LOADING = "APP/UPDATE_IS_LOADING";
export const UPDATE_SHOW_NAV_ITEMS = "APP/UPDATE_SHOW_NAV_ITEMS";
export const UPDATE_ITEMS_AMOUNT = "APP/UPDATE_ITEMS_AMOUNT";
export const UPDATE_CURRENT_MENU_ITEM = "APP/UPDATE_CURRENT_MENU_ITEM";
